### ISSUE TITLE
Disable/Skip CompressionHandler when NSUrlSessionHandler is used as final handler.

### ISSUE THREAD

**Issue by peombwa** [microsoftgraph/msgraph-sdk-dotnet#482]
## Issue
`NSUrlSessionHandler` - `Xamarin.iOS` - handles decompression out of the box and doesn't provide an option to turn it off. This throws a [System.IO.IOException: Corrupted data ReadInternal](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/413#issuecomment-495556463) exception when our `CompressionHandler` is used alongside `NSUrlSessionHandler` as described in issue #413.

## Workaround
The current work around involves creating a new pipeline without the CompressionHandler.
```cs
#if __IOS__
            var innerHandler = new NSUrlSessionHandler { AllowAutoRedirect = false };
            var handlers = GraphClientFactory.CreateDefaultHandlers(authProvider);
            // Remove CompressionHandler from pipeline when using NSUrlSessionHandler.
            handlers.Remove(handlers.FirstOrDefault((h) => h.GetType().Equals(typeof(CompressionHandler)))); // We need to provide a method to remove handlers by type. 
            var pipeline = GraphClientFactory.CreatePipeline(handlers , innerHandler);
            httpProvider = new HttpProvider(pipeline, true, new Serializer());
```

**Comment by peombwa** [comment]
This has been fixed in https://www.nuget.org/packages/Microsoft.Graph.Core/1.16.0-preview.2.

**Comment by tipa** [comment]
It looks like it still throws an `System.IO.IOException: Corrupted data ReadInternal` on iOS when using Microsoft.Graph.Core v1.16.0-preview.2 & Microsoft.Graph v1.15.0

**Comment by peombwa** [comment]
Thanks for the feedback. I'll try and repro it on my end. Are you using a custom HttpProvider by any chance?

**Comment by tipa** [comment]
No, I was calling the new `GraphServiceClient(baseUrl, authenticationProvider)` constructor without using the httpProvider parameter

**Comment by peombwa** [comment]
@tipa, I have been able to repro the exception and we've released https://www.nuget.org/packages/Microsoft.Graph.Core/1.16.0-preview.3 to fix it. Our `CompressionHandler` was still present in the middleware pipeline, and this fix skips it when creating a new middleware pipeline on Xamarin.iOS.
