### ISSUE TITLE
CreateUploadSession fails

### ISSUE THREAD

**Issue by armadiljo** [microsoftgraph/msgraph-sdk-dotnet#560]
**Describe the bug**
In version 1.18 CreateUploadSession fails with error "The request is malformed or incorrect", while the same code works fine in version 1.17.

**To Reproduce**
Code that works in version 1.17, but fails in version 1.18.
`

                DriveItemUploadableProperties diup = new DriveItemUploadableProperties();
 
                diup.AdditionalData = new Dictionary<string, object>();
                diup.AdditionalData.Add("@microsoft.graph.conflictBehavior", "replace");

                var uploadSession = await graphClient
                    .Drives["<some-drive-id>"]
                    .Root
                    .ItemWithPath("/TestFile.txt")
                    .CreateUploadSession(diup)
                    .Request()
                    .PostAsync();
`

**Expected behavior**
Unless I am doing something wrong in the code above, an UploadSession should be created successfully.
 
[AB#7302](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7302)

**Comment by darrelmiller** [comment]
We are not aware of any changes in 1.18 that might affect this.  We will investigate.  Could you provide us with a requestId of a failure.  Thanks.

**Comment by armadiljo** [comment]
I saved one from yesterday. I hope it helps.

Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: invalidRequest
Message: The request is malformed or incorrect.
Inner error:
	AdditionalData:
	request-id: feee3275-cac7-43b6-92f9-d1a66378bf16
	date: 21.10.2019 14:56:59
ClientRequestId: feee3275-cac7-43b6-92f9-d1a66378bf16

**Comment by armadiljo** [comment]
(sorry, just made a mess by clicking the wrong button)

I saved one from yesterday. I hope it helps.

Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: invalidRequest
Message: The request is malformed or incorrect.
Inner error:
AdditionalData:
request-id: feee3275-cac7-43b6-92f9-d1a66378bf16
date: 21.10.2019 14:56:59
ClientRequestId: feee3275-cac7-43b6-92f9-d1a66378bf16

**Comment by andrueastman** [comment]
Version 1.18 now sets the Odata Type property in the complex types in the model for [DriveItemUploadableProperties ](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/74e26ff12fa5f99275d9d9ebd99a502ea34557d4/src/Microsoft.Graph/Models/Generated/DriveItemUploadableProperties.cs#L30) therefore the effective request body sent out now looks like this.
```json
{
"item": 
  {
    "@odata.type":"microsoft.graph.driveItemUploadableProperties",
    "@microsoft.graph.conflictBehavior":"replace"
  }
}
```
whereas before in version 1.17 the effective payload looked like this as the odata type property was not set.

```json
{
"item": 
  {
    "@microsoft.graph.conflictBehavior":"replace"
  }
}
```

From my testing, this looks to affect only work/school accounts. On using a personal account with 1.18 the upload session is created fine. 
Adding the "@odata.type" with a school/work account throws the same error on testing the same on graph explorer.

This issue may also be loosely related to open issue #364 and looks like the service isn't liking the added field when one is using a school/work account

cc @darrelmiller @MIchaelMainer

**Comment by MIchaelMainer** [comment]
@ificator Are you aware of this behavior where odata.type set on DriveItemUploadableProperties for work/school account results in an Invalid request?

**Comment by tipa** [comment]
Having the same issue, I am also getting reported "Bad request" errors from my users

**Comment by andrueastman** [comment]
We have released [Microsoft.Graph v1.19](https://www.nuget.org/packages/Microsoft.Graph/) that should resolve this. Please check it out and let us know if it works out for you. 
@tipa @armadiljo

**Comment by MIchaelMainer** [comment]
@tipa and @armadiljo 

The service should gracefully ignore the odatatype property.  That is the expected behavior. 

I *temporarily* mitigated this by manually removing the odatatype from the DriveItemUploadableProperties property after the class was generated. The problem is the next time the file is generated, the odatatype will be set and we are uncertain about whether the service API behavior will be updated at that point. 

The client workaround is to set the odatatype property to null:

```csharp
DriveItemUploadableProperties diup = new DriveItemUploadableProperties() { ODataType = null}
```

**Comment by armadiljo** [comment]
@MIchaelMainer 

I can confirm the following:
  - The project with version 1.17 works fine.
  - Then upgraded to version 1.18 that fails.
  - Finally upgraded to version 1.19 that works fine again.
  - Additionally tried with setting the ODataType property to null on both versions 1.19 and 1.18 and that also worked fine.

**Comment by MIchaelMainer** [comment]
This issue will remain open until this is addressed on the service.

**Comment by tipa** [comment]
Is this problem still present in 1.20 or not?

**Comment by MIchaelMainer** [comment]
This issue still exists in the Microsoft Graph service API. This issue is experienced in 1.20 and the mitigation is to set the ODataType property to null.

**Comment by tipa** [comment]
It's a kind of frustrating experience to find out that with every other update of the library, my existing code breaks and I am forced to downgrade and issue hotfix updates to my app... Wish this would happen less regularly.

**Comment by tipa** [comment]
When is this issue expected to be fixed so that we can remove the workaround?

**Comment by mhagesfeld** [comment]
I am using Microsoft.graph.Beta 0.12 - is this not fixed there?

**Comment by mhagesfeld** [comment]
> I am using Microsoft.graph.Beta 0.12 - is this not fixed there?

This does work if you nullify data type

**Comment by Kronos11** [comment]
Yet another person who ran into this quite frustrating issue. I would really think a minor release would not break functionality like this. Seems like this overwrite functionality is quite easy to abstract so we don't have to add custom properties even.

**Comment by tipa** [comment]
So this morning I wake up with 100 mails in my inbox from users reporting that the OneDrive sync fails completely, because of this error when creating an upload session:
```
Microsoft.Graph.ServiceException: Code: InternalServerError
Message: Object reference not set to an instance of an object.
```

*What is going on? How can this happen?*

**Comment by tipa** [comment]
After some digging it seems like this library is using a wrong endpoint.
[As of the docs](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#request), the endpoint is `/createUploadSession` but his library is using [/microsoft.graph.createUploadSession](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/05231d6229a5693a5ac675d42360e77b56c17168/src/Microsoft.Graph/Requests/Generated/DriveItemRequestBuilder.cs#L225) ....

**Comment by rikyuz** [comment]
Yeah, it's broken again. Has Microsoft not implemented test automation for these?

**Comment by darrelmiller** [comment]
@tipa I just tried this in Graph Explorer and it worked... https://graph.microsoft.com/v1.0/me/drive/root:/foo:/microsoft.graph.createUploadSession   Are you using the V1.0 API?

**Comment by rikyuz** [comment]
@darrelmiller I'm facing the same issue as @tipa and I'm using the v1.0 API.

**Comment by tipa** [comment]
Yes I am using `v1.0`, but also happens with `beta`. What other versions do exist?

**Comment by IvanBil** [comment]
The same issue today morning. v1.0 API with Microsoft.Graph 1.21

**Comment by darrelmiller** [comment]
Would someone be able to share a request-id with me?  You can email me at darrel.miller@microsoft.com

**Comment by IvanBil** [comment]
> Would someone be able to share a request-id with me? You can email me at [darrel.miller@microsoft.com](mailto:darrel.miller@microsoft.com)

Done

**Comment by tipa** [comment]
Bug still present, would love to remove the `ODataType = null` workaround at some point.

```
Status Code: BadRequest 
Microsoft.Graph.ServiceException: Code: invalidRequest 
Message: Invalid request 
Inner error: 
        AdditionalData: 
        date: 2020-07-16T21:10:06 
        request-id: 7bbcfc18-a619-4d97-9657-9a37c388b375 
ClientRequestId: 7bbcfc18-a619-4d97-9657-9a37c388b375 
```

**Comment by relair** [comment]
The bug is still there in version 3.21.0 of Graph library
when you use CreateUploadSession with no parameters it works fine:
 var uploadSession = await graphClient.Drive.Items["01KGPRHTV6Y2GOVW7725BZO354PWSELRRZ"].ItemWithPath("_hamilton.png").CreateUploadSession().Request().PostAsync();
But if you provide even the default DriveItemUpdatableProperties it fails:
graphClient.Drive.Items["01KGPRHTV6Y2GOVW7725BZO354PWSELRRZ"].ItemWithPath("_hamilton.png").CreateUploadSession(new DriveItemUpdatableProperties()).Request().PostAsync();

I have found it is because it adds unexpected ODataType property into the body. I do have workaround of setting it to null after creating the request object: driveItemCreateUploadSessionRequest.RequestBody.Item.ODataType = null but it would be good if such measure wouldn't be needed.

You should probably add a test in https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/tests/Microsoft.Graph.DotnetCore.Test/Requests/Functional/OneDriveTests.cs to cover a case with using DriveItemUpdatableProperties as that's probably the reason that you've missed that bug for so long.

**Comment by andrueastman** [comment]
This is resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/993 and https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534 and should now be available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6
