### ISSUE TITLE
Creation of team fails from Azure Function 2.0 and .NET Core 2.2

### ISSUE THREAD

**Issue by adrichema** [microsoftgraph/msgraph-sdk-dotnet#566]
**Describe the bug**
The creation/upgrading of a new team failes when using the SDK from a Azure Function based on .NET Core 2.2.

Message: Could not find member '@odata.type' on object of type 'TeamMemberSettings'. Path 'memberSettings['@odata.type']', line 1, position 67.,Could not find member '@odata.type' on object of type 'TeamGuestSettings'. Path 'guestSettings['@odata.type']', line 1, position 204.,Could not find member '@odata.type' on object of type 'TeamMessagingSettings'. Path 'messagingSettings['@odata.type']', line 1, position 342.,Could not find member '@odata.type' on object of type 'TeamFunSettings'. Path 'funSettings['@odata.type']', line 1, position 466.,Could not find member '@odata.type' on object of type 'Team'. Path '['@odata.type']', line 1, position 521.

**To Reproduce**
Create a new team / upgrade a group from an Azure Function based on .NET Core 2.2 using the latest version of the Graph SDK. I submitted the following team object:

 Team newTeam = new Team()
                {
                    GuestSettings = new TeamGuestSettings
                    {
                        AllowCreateUpdateChannels = false,
                        AllowDeleteChannels = false
                    },
                    MemberSettings = new TeamMemberSettings
                    {
                        AllowCreateUpdateChannels = false
                    },
                    MessagingSettings = new TeamMessagingSettings
                    {
                        AllowUserEditMessages = true,
                        AllowUserDeleteMessages = true
                    },
                    FunSettings = new TeamFunSettings
                    {
                        AllowGiphy = true,
                        GiphyContentRating = GiphyRatingType.Strict
                    }
                };

**Expected behavior**
A new team should created instead of a warning.

**Related links**
I found this issue also on stackoverflow, i tried to add the Odata package, but this did not solve the issue.
https://stackoverflow.com/questions/58420993/could-not-find-member-odata-type-on-object-of-type-teammembersettings
 
[AB#7308](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7308)

**Comment by MIchaelMainer** [comment]
The error message isn't clear that the Teams service doesn't know how to handle odata.type. Ideally, it should ignore it if it is unexpected.

The reason why you are seeing this now is that we now set the previously not set odata.type property on all models. 

The fix:

```csharp
Team newTeam = new Team()
{
	GuestSettings = new TeamGuestSettings
	{
		AllowCreateUpdateChannels = false,
		AllowDeleteChannels = false,
		ODataType = null
	},
	MemberSettings = new TeamMemberSettings
	{
		AllowCreateUpdateChannels = false,
		ODataType = null
	},
	MessagingSettings = new TeamMessagingSettings
	{
		AllowUserEditMessages = true,
		AllowUserDeleteMessages = true,
		ODataType = null
	},
	FunSettings = new TeamFunSettings
	{
		AllowGiphy = true,
		GiphyContentRating = GiphyRatingType.Strict,
		ODataType = null
	},
	ODataType = null
};
```

**Comment by adrichema** [comment]
Shouldn't this be documented? It took me 2 days, after that i decided to go back to version 1.0.17.

**Comment by MIchaelMainer** [comment]
@adrichema You are correct, this should be documented. We are missing a lot of documentation. I apologize to you and anyone else who have encountered this scenario. I will feed this back to our service team.

**Comment by habex-ch** [comment]
Will this be fixed in the upcoming version?

**Comment by darrelmiller** [comment]
We are working on a workaround in our code generator until the services can fix their issues.

**Comment by adrichema** [comment]
Issue is still not fixed. Still get a BadRequest errror with message: Could not find member '@odata.type' on object of type 'TeamMemberSettings'.

**Comment by dnyaneshwar-surywanshi** [comment]
Team newTeam = new Team()
                {
                    GuestSettings = new TeamGuestSettings
                    {
                        AllowCreateUpdateChannels = false,
                        AllowDeleteChannels = false,
                        ODataType = null
                    },
                    MemberSettings = new TeamMemberSettings
                    {
                        AllowCreateUpdateChannels = false,
                        ODataType = null
                    },
                    MessagingSettings = new TeamMessagingSettings
                    {
                        AllowUserEditMessages = true,
                        AllowUserDeleteMessages = true,
                        ODataType = null
                    },
                    FunSettings = new TeamFunSettings
                    {
                        AllowGiphy = true,
                        GiphyContentRating = GiphyRatingType.Strict,
                        ODataType = null
                    },
                    DisplayName = teamGroup.teamName,
                    ODataType = null
                };

                //var groupId = graphClient.Groups.RequestUrl;
                await graphClient.Groups[teamGroup.groupId].Team
                    .Request()
                    .CreateAsync(newTeam);

Can someone please told me how I can add Team members in Team object also i want to give Team name I am using DisplayName property for that but still my Azure group name and created team name is same

**Comment by adrichema** [comment]
> Team newTeam = new Team()
> {
> GuestSettings = new TeamGuestSettings
> {
> AllowCreateUpdateChannels = false,
> AllowDeleteChannels = false,
> ODataType = null
> },
> MemberSettings = new TeamMemberSettings
> {
> AllowCreateUpdateChannels = false,
> ODataType = null
> },
> MessagingSettings = new TeamMessagingSettings
> {
> AllowUserEditMessages = true,
> AllowUserDeleteMessages = true,
> ODataType = null
> },
> FunSettings = new TeamFunSettings
> {
> AllowGiphy = true,
> GiphyContentRating = GiphyRatingType.Strict,
> ODataType = null
> },
> DisplayName = teamGroup.teamName,
> ODataType = null
> };
> 
> ```
>             //var groupId = graphClient.Groups.RequestUrl;
>             await graphClient.Groups[teamGroup.groupId].Team
>                 .Request()
>                 .CreateAsync(newTeam);
> ```
> 
> Can someone please told me how I can add Team members in Team object also i want to give Team name I am using DisplayName property for that but still my Azure group name and created team name is same

This has nothing to do with the initial description of this topic, please don't hijack this topic!

**Comment by andrueastman** [comment]
This is resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/993 and https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/534 and should now be available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6
